### ISSUE TITLE
Idea: Add a Pop OS Wallpaper

### ISSUE THREAD

**Issue by PaladinAOE2** [dxnst/nord-backgrounds#1]

**Comment by dxnst** [comment]
sure!

**Comment by PaladinAOE2** [comment]
Thanks!

**Comment by PaladinAOE2** [comment]
![element (1)](https://user-images.githubusercontent.com/62720666/110801271-0d2ad100-824b-11eb-97b9-1f7bfb3ad7a9.png)
Heres a logo for reference
