### ISSUE TITLE
How do you create the wallpapers in avogadro.io folder?

### ISSUE THREAD

**Issue by xukai92** [dxnst/nord-backgrounds#2]
I'm interested in creating some for other molecules.
Can you give me some hints on how you make the existing ones?
Thanks!

**Comment by dxnst** [comment]
Sorry, seems like the website for avogadr.io is down, but I used to edit the URL to match the colors and molecular structure I wanted. Right now I guess the only way to make more of those wallpapers is to run a local instance of the [avogadrio API](https://github.com/lambdacasserole/avogadrio).

**Comment by xukai92** [comment]
Thanks for the information.
After you generate the molecules, do you use ImageGoNord to nordify them, or something else?

**Comment by dxnst** [comment]
No, I don´t use ImageGoNord for that. You can save the generated molecules as a SVG or PNG file and then create a template in GIMP or Photoshop and replace the colors for the ones you want.

**Comment by xukai92** [comment]
I don't know how to create such a template. Is this something that you can share (saying including in this repo)?

**Comment by czechbol** [comment]
I realize this is an old issue but I created a python package to do this: https://github.com/czechbol/avogadr-py

It's not the greatest program ever but gets the job done, is reasonably easy to use and it's configurable.

**Comment by xukai92** [comment]
Thanks for the pointer! I think we can close this issue now.
