### ISSUE TITLE
Just a note for you

### ISSUE THREAD

**Issue by czechbol** [dxnst/nord-backgrounds#5]
### Hey, I made a fork a couple days earlier.
Instead of Nord I wanted to use the TokyoNight theme so I replaced the colour scheme and added a bunch of stuff.

Like the background source files for example, 2560x1440 exports, every avogadr.io background in 7 different colours, new companies category, new operating systems, new software and programming languages ... 

**I just want to create this issue because if you plan on continuing to maintain this repo, my fork should provide anything you need to get up to date with me fairly easily and quickly. I won't create PRs since I strayed to a different colour scheme.**

You can find the fork here: https://github.com/czechbol/tokyonight-backgrounds

#### To export the SVGs I used these CLI commands:
*You have to be in the same folder as the svg files or modify the find command*
```
find ./*.svg -type f -exec inkscape --export-type="png" -w 1920 -h 1080 {} \;
find ./*.svg -type f -exec inkscape --export-type="png" -w 2560 -h 1440 {} \;
find ./*.svg -type f -exec inkscape --export-type="png" {} \; # source files are 3840x2160
```
*Note: I had troubles with a few icons so I exported a few (like 2 or 3) on my windows machine with Adobe Illustrator.*

**I also created a python package that can download all those avogadr.io backgrounds you need, you can see it [here](https://github.com/czechbol/avogadr-py).**

With this, I want to thank you for your contribution, I'd been using these backgrounds for about a year until I switched to TokyoNight a few days ago so I felt like I had to contribute to this project in some way.

_Feel free to ignore this issue, close it or do whatever you want with it. All I wanted was for you to notice this._

**Comment by dxnst** [comment]
I cannot thank you enough for this!

I started this project as a little hobby, never thought it would grow this much, and I do hope great success for your project! I myself have been quite interested in the tokyonight colorscheme.

Maybe in the near future I'll add new ideas or more items for the current categories. Currently I'm kinda busy doing an internship for my medical career (maybe I should add some cool drugs lol).

Again, thank you for your contribution! And I'm really glad you enjoyed my little project :smile: !
